name: Deploy to AKS

on:
  push:
    branches: [ main ]
    paths:
    - Chapter15/**
    - .github/workflows/pipeline.yaml
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: acr login
        run: az acr login -n ${{ env.REGISTRY_NAME }}
        
      # Build container image
      - name: Build and push container image
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./Chapter15
          tags: ${{ env.REGISTRY_NAME }}.azurecr.io/website:${{ github.run_number }}
          
      - name: AKS set context
        uses: azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          resource-group: ${{ env.RESOURCE_GROUP }}
          cluster-name: ${{ env.CLUSTER_NAME }}
          
      # Deploy to AKS
      - name: Apply Kubernetes manifests
        run: |
          helm upgrade website Chapter15/website --install \
           --set image.repository=${{ env.REGISTRY_NAME }}.azurecr.io/website/website \
           --set image.tag=${{ github.run_number }}

# Replace placeholders with your values:
env:
  RESOURCE_GROUP: aks-rg
  CLUSTER_NAME: agic-aks
  REGISTRY_NAME: handsonaks007
  IMAGE_NAME: website
